INSERT INTO accounts VALUES ('1', 'LJ8NY3hK9dDzPxbP0zFBCRgyDlQBtlSB6o4d0b58dyPk');
INSERT INTO accounts VALUES ('2', 'DdqvHp5GehhCxhYcFT1cs6RPRXrRTcitSDznlkx8R5T8');
INSERT INTO accounts VALUES ('3', '7ivKfZrvIEYRWDZe8zSvCrJLR2qrIxYFPQileqUhRqXE');
